stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    outs:
    - data/raw/iris.csv
    params:
    - base
    - data_load
  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - data/processed/featured_iris.csv
    - src/stages/data_split.py
    outs:
    - data/processed/test_iris.csv
    - data/processed/train_iris.csv
    params:
    - base
    - data_split
    - featurize
  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - data/processed/test_iris.csv
    - models/model.joblib
    - params.yaml
    - src/stages/evaluate.py
    outs:
    - reports/confusion_matrix.png
    metrics:
    - reports/metrics.json
  featurize:
    cmd: python src/stages/featurize.py --config=params.yaml
    deps:
    - data/raw/iris.csv
    - src/stages/featurize.py
    outs:
    - data/processed/featured_iris.csv
    params:
    - base
    - featurize
  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
    - data/processed/train_iris.csv
    - src/stages/train.py
    outs:
    - models/model.joblib
    params:
    - base
    - train
