stages:
  train:
    cmd: python pretrained_model_tuner.py
    deps:
    - hymenoptera_data/
    - pretrained_model_tuner.py
    outs:
    - dvclive/metrics.json:
        cache: false
    - model.pt
metrics:
- results/metrics.json
- dvclive/metrics.json
plots:
- results/plots/metrics:
    x: step
- dvclive/plots/metrics:
    x: step
